version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "7860:7860"
    environment:
      - HFAPI=your_huggingface_key
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
